# Generated by Django 5.1.7 on 2025-04-14 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_rename_independece_independence_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='independence',
            old_name='degree_of_independence',
            new_name='independence',
        ),
    ]
