# Generated by Django 5.1.7 on 2025-04-14 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_independece_senior'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Independece',
            new_name='Independence',
        ),
        migrations.RenameField(
            model_name='independence',
            old_name='degree_of_independece',
            new_name='degree_of_independence',
        ),
        migrations.RenameField(
            model_name='senior',
            old_name='degree_of_indepence',
            new_name='independence',
        ),
    ]
